fix test
#INFSYS-3701

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -30,84 +30,89 @@ jobs:
       fail-fast: false
 
     steps:
-#      - name: "Checkout"
-#        uses: "actions/checkout@v2"
-#
-#      - name: "Setup PHP cache environment"
-#        id: "extcache"
-#        uses: "shivammathur/cache-extensions@v1"
-#        with:
-#          php-version: "${{ matrix.php-version }}"
-#          extensions: "${{ env.extensions }}"
-#          key: "${{ env.cache-version }}"
-#
-#      - name: "Cache PHP extensions"
-#        uses: "actions/cache@v4"
-#        with:
-#          path: "${{ steps.extcache.outputs.dir }}"
-#          key: "${{ steps.extcache.outputs.key }}"
-#          restore-keys: "${{ steps.extcache.outputs.key }}"
-#
-#      - name: "Install PHP"
-#        uses: "shivammathur/setup-php@v2"
-#        with:
-#          php-version: "${{ matrix.php-version }}"
-#          extensions: "${{ env.extensions }}"
-#          tools: "composer:${{ env.composer-version }}"
-#          coverage: "${{ env.coverage }}"
-#        env:
-#          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-#
-#      - name: "Setup problem matchers for PHP"
-#        run: 'echo "::add-matcher::${{ runner.tool_cache }}/php.json"'
-#
-#      - name: "Get Composer cache directory"
-#        id: "composercache"
-#        run: 'echo "::set-output name=dir::$(composer config cache-files-dir)"'
-#
-#      - name: "Cache PHP dependencies"
-#        uses: "actions/cache@v4"
-#        with:
-#          path: "${{ steps.composercache.outputs.dir }}"
-#          key: "${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}"
-#          restore-keys: "${{ runner.os }}-composer-"
-#
-#      - name: "Install dependencies"
-#        run: "${{ env.composer-install }}"
-#
-#      - name: "Env variables"
-#        run: |
-#          echo "API_MERCHANT=${{ secrets.API_MERCHANT }}" >> .env
-#          echo "API_SECRET=${{ secrets.API_SECRET }}" >> .env
-#          echo "API_URL=${{ secrets.API_URL }}" >> .env
-#          echo "APPLICATION_ENV='sdk-github'" >> .env
-#          echo "CF_ACCESS_CLIENT_ID=${{ secrets.CF_ACCESS_ID }}" >> .env
-#          echo "CF_ACCESS_CLIENT_SECRET=${{ secrets.CF_ACCESS_SECRET }}" >> .env
-
-#      - name: "Check access to test enviroment"
-#        run: |
-#          curl -H "CF-Access-Client-Id: ${{ secrets.CF_ACCESS_ID }}" \
-#          -H "CF-Access-Client-Secret: ${{ secrets.CF_ACCESS_SECRET }}" \
-#          -v https://payments.comgate-test.cz/core/index/hello 2>&1 | grep 'HTTP/2 200'
-
       - name: "Check current IP"
         run: |
           agentIP=$(curl -s https://api.ipify.org/)
           echo $agentIP
+          if [[ ! $agentIP == 40.* ]]; then
+            echo "Error: IP address ($agentIP) does not start with '40.'"
+            exit 1
+          fi
+          echo "IP check passed.
 
-#      - name: "Build Codeception actors"
-#        run: "vendor/bin/codecept build -v"
-#
-#      - name: "Regenerate autoloader"
-#        run: "composer dump-autoload --optimize"
+      - name: "Checkout"
+        uses: "actions/checkout@v2"
 
-#      - name: Run Codeception Tests
-#        run: |
-#          vendor/bin/codecept run
+      - name: "Setup PHP cache environment"
+        id: "extcache"
+        uses: "shivammathur/cache-extensions@v1"
+        with:
+          php-version: "${{ matrix.php-version }}"
+          extensions: "${{ env.extensions }}"
+          key: "${{ env.cache-version }}"
 
-#      - name: "Upload test output"
-#        if: ${{ failure() }}
-#        uses: actions/upload-artifact@v4
-#        with:
-#          name: output
-#          path: tests/**/output
+      - name: "Cache PHP extensions"
+        uses: "actions/cache@v4"
+        with:
+          path: "${{ steps.extcache.outputs.dir }}"
+          key: "${{ steps.extcache.outputs.key }}"
+          restore-keys: "${{ steps.extcache.outputs.key }}"
+
+      - name: "Install PHP"
+        uses: "shivammathur/setup-php@v2"
+        with:
+          php-version: "${{ matrix.php-version }}"
+          extensions: "${{ env.extensions }}"
+          tools: "composer:${{ env.composer-version }}"
+          coverage: "${{ env.coverage }}"
+        env:
+          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: "Setup problem matchers for PHP"
+        run: 'echo "::add-matcher::${{ runner.tool_cache }}/php.json"'
+
+      - name: "Get Composer cache directory"
+        id: "composercache"
+        run: 'echo "::set-output name=dir::$(composer config cache-files-dir)"'
+
+      - name: "Cache PHP dependencies"
+        uses: "actions/cache@v4"
+        with:
+          path: "${{ steps.composercache.outputs.dir }}"
+          key: "${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}"
+          restore-keys: "${{ runner.os }}-composer-"
+
+      - name: "Install dependencies"
+        run: "${{ env.composer-install }}"
+
+      - name: "Env variables"
+        run: |
+          echo "API_MERCHANT=${{ secrets.API_MERCHANT }}" >> .env
+          echo "API_SECRET=${{ secrets.API_SECRET }}" >> .env
+          echo "API_URL=${{ secrets.API_URL }}" >> .env
+          echo "APPLICATION_ENV='sdk-github'" >> .env
+          echo "CF_ACCESS_CLIENT_ID=${{ secrets.CF_ACCESS_ID }}" >> .env
+          echo "CF_ACCESS_CLIENT_SECRET=${{ secrets.CF_ACCESS_SECRET }}" >> .env
+
+      - name: "Check access to test enviroment"
+        run: |
+          curl -H "CF-Access-Client-Id: ${{ secrets.CF_ACCESS_ID }}" \
+          -H "CF-Access-Client-Secret: ${{ secrets.CF_ACCESS_SECRET }}" \
+          -v https://payments.comgate-test.cz/core/index/hello 2>&1 | grep 'HTTP/2 200'
+
+      - name: "Build Codeception actors"
+        run: "vendor/bin/codecept build -v"
+
+      - name: "Regenerate autoloader"
+        run: "composer dump-autoload --optimize"
+
+      - name: Run Codeception Tests
+        run: |
+          vendor/bin/codecept run
+
+      - name: "Upload test output"
+        if: ${{ failure() }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: output
+          path: tests/**/output
